version: "3"

services:
  n8n:
    restart: unless-stopped
    build:
      context: .
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=UTC
      - N8N_LOG_LEVEL=debug
    volumes:
      - n8n-data:/home/node/.n8n

volumes:
  n8n-data:

