services:
  n8n:
    restart: unless-stopped
    build:
      context: .
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=UTC
      - N8N_LOG_LEVEL=debug
      - N8N_SECURE_COOKIE=false
      - N8N_HOST=0.0.0.0
      - N8N_PROTOCOL=http
      - N8N_DEV_RELOAD=true
    volumes:
      - n8n-data:/home/node/.n8n

volumes:
  n8n-data:

